mysql:
  host: 127.0.0.1
  port: 3306
  db: file
  user: root
  password: a
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show-line: true
  log-in-console: true
system:
  host: "0.0.0.0"
  port: 8080
  #  env: dev
  env: release
# true 生成数据库
# false 不生成数据库
create_db:
  is_create: false
file_size:
  size: 15 # 单位M
jwt:
  secret: xxxx
  expires: 2  # 单位小时
  issuer: "1234"
