// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"FengfengStudy/models/orm/model"
)

func newClass(db *gorm.DB, opts ...gen.DOOption) class {
	_class := class{}

	_class.classDo.UseDB(db, opts...)
	_class.classDo.UseModel(&model.Class{})

	tableName := _class.classDo.TableName()
	_class.ALL = field.NewAsterisk(tableName)
	_class.ClassID = field.NewInt32(tableName, "class_id")
	_class.Name = field.NewString(tableName, "name")

	_class.fillFieldMap()

	return _class
}

type class struct {
	classDo

	ALL     field.Asterisk
	ClassID field.Int32
	Name    field.String

	fieldMap map[string]field.Expr
}

func (c class) Table(newTableName string) *class {
	c.classDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c class) As(alias string) *class {
	c.classDo.DO = *(c.classDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *class) updateTableName(table string) *class {
	c.ALL = field.NewAsterisk(table)
	c.ClassID = field.NewInt32(table, "class_id")
	c.Name = field.NewString(table, "name")

	c.fillFieldMap()

	return c
}

func (c *class) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *class) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["class_id"] = c.ClassID
	c.fieldMap["name"] = c.Name
}

func (c class) clone(db *gorm.DB) class {
	c.classDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c class) replaceDB(db *gorm.DB) class {
	c.classDo.ReplaceDB(db)
	return c
}

type classDo struct{ gen.DO }

func (c classDo) Debug() *classDo {
	return c.withDO(c.DO.Debug())
}

func (c classDo) WithContext(ctx context.Context) *classDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c classDo) ReadDB() *classDo {
	return c.Clauses(dbresolver.Read)
}

func (c classDo) WriteDB() *classDo {
	return c.Clauses(dbresolver.Write)
}

func (c classDo) Session(config *gorm.Session) *classDo {
	return c.withDO(c.DO.Session(config))
}

func (c classDo) Clauses(conds ...clause.Expression) *classDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c classDo) Returning(value interface{}, columns ...string) *classDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c classDo) Not(conds ...gen.Condition) *classDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c classDo) Or(conds ...gen.Condition) *classDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c classDo) Select(conds ...field.Expr) *classDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c classDo) Where(conds ...gen.Condition) *classDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c classDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *classDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c classDo) Order(conds ...field.Expr) *classDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c classDo) Distinct(cols ...field.Expr) *classDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c classDo) Omit(cols ...field.Expr) *classDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c classDo) Join(table schema.Tabler, on ...field.Expr) *classDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c classDo) LeftJoin(table schema.Tabler, on ...field.Expr) *classDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c classDo) RightJoin(table schema.Tabler, on ...field.Expr) *classDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c classDo) Group(cols ...field.Expr) *classDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c classDo) Having(conds ...gen.Condition) *classDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c classDo) Limit(limit int) *classDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c classDo) Offset(offset int) *classDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c classDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *classDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c classDo) Unscoped() *classDo {
	return c.withDO(c.DO.Unscoped())
}

func (c classDo) Create(values ...*model.Class) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c classDo) CreateInBatches(values []*model.Class, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c classDo) Save(values ...*model.Class) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c classDo) First() (*model.Class, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Class), nil
	}
}

func (c classDo) Take() (*model.Class, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Class), nil
	}
}

func (c classDo) Last() (*model.Class, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Class), nil
	}
}

func (c classDo) Find() ([]*model.Class, error) {
	result, err := c.DO.Find()
	return result.([]*model.Class), err
}

func (c classDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Class, err error) {
	buf := make([]*model.Class, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c classDo) FindInBatches(result *[]*model.Class, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c classDo) Attrs(attrs ...field.AssignExpr) *classDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c classDo) Assign(attrs ...field.AssignExpr) *classDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c classDo) Joins(fields ...field.RelationField) *classDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c classDo) Preload(fields ...field.RelationField) *classDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c classDo) FirstOrInit() (*model.Class, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Class), nil
	}
}

func (c classDo) FirstOrCreate() (*model.Class, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Class), nil
	}
}

func (c classDo) FindByPage(offset int, limit int) (result []*model.Class, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c classDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c classDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c classDo) Delete(models ...*model.Class) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *classDo) withDO(do gen.Dao) *classDo {
	c.DO = *do.(*gen.DO)
	return c
}
