// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameClassUser = "class_user"

// ClassUser mapped from table <class_user>
type ClassUser struct {
	ClassID        int32  `gorm:"column:class_id;not null" json:"class_id"`
	StuID          int32  `gorm:"column:stu_id;not null" json:"stu_id"`
	Name           string `gorm:"column:name;not null" json:"name"`
	PermissionType int32  `gorm:"column:permission_type;not null" json:"permission_type"` // 1:管理员 2:普通用户
	Username       string `gorm:"column:username;not null" json:"username"`
}

// TableName ClassUser's table name
func (*ClassUser) TableName() string {
	return TableNameClassUser
}
