// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourse = "course"

// Course mapped from table <course>
type Course struct {
	CourseID      int32     `gorm:"column:course_id;primaryKey;autoIncrement:true" json:"course_id"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	ClassID       int32     `gorm:"column:class_id;not null" json:"class_id"`
	PublisherName string    `gorm:"column:publisher_name;not null" json:"publisher_name"`
	Deadline      time.Time `gorm:"column:deadline" json:"deadline"` // 截止时间
	StuID         int32     `gorm:"column:stu_id;not null" json:"stu_id"`
	FileType      string    `gorm:"column:file_type;not null" json:"file_type"`
	Username      string    `gorm:"column:username;not null" json:"username"`
	CourseName    string    `gorm:"column:course_name;not null" json:"course_name"`
}

// TableName Course's table name
func (*Course) TableName() string {
	return TableNameCourse
}
