// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourse = "course"

// Course mapped from table <course>
type Course struct {
	CourseID   int32     `gorm:"column:course_id;primaryKey;autoIncrement:true" json:"course_id"`
	CourseName string    `gorm:"column:course_name;not null" json:"course_name"`
	ClassID    int32     `gorm:"column:class_id;not null" json:"class_id"`
	Username   string    `gorm:"column:username;not null" json:"username"` // 发布者名
	Deadline   time.Time `gorm:"column:deadline" json:"deadline"`          // 截止时间
	StuID      int32     `gorm:"column:stu_id;not null" json:"stu_id"`     // 发布者id
}

// TableName Course's table name
func (*Course) TableName() string {
	return TableNameCourse
}
