// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	StuID    int32  `gorm:"column:stu_id;primaryKey" json:"stu_id"`
	Name     string `gorm:"column:name;not null" json:"name"`
	Password string `gorm:"column:password;not null" json:"password"`
	Username string `gorm:"column:username;not null" json:"username"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
