// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWorklist = "worklist"

// Worklist mapped from table <worklist>
type Worklist struct {
	WorkID     int32     `gorm:"column:work_id;primaryKey;autoIncrement:true" json:"work_id"` // 工作流水号
	CourseID   int32     `gorm:"column:course_id;not null" json:"course_id"`                  // 任务id
	CourseName string    `gorm:"column:course_name;not null" json:"course_name"`              // 任务名称
	Status     int32     `gorm:"column:status;not null" json:"status"`                        // 提交人数
	StuID      int32     `gorm:"column:stu_id;not null" json:"stu_id"`
	Deadline   time.Time `gorm:"column:deadline;not null" json:"deadline"`
}

// TableName Worklist's table name
func (*Worklist) TableName() string {
	return TableNameWorklist
}
